name: brew pr-pull
on:
  pull_request_target:
    types:
      - labeled

jobs:
  pr-pull:
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      packages: write
      pull-requests: write
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-latest
    env:
      HOMEBREW_NO_INSTALL_FROM_API: 1
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ github.token }}

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: brew install-bundler-gems

      - name: Set up git
        uses: Homebrew/actions/git-user-config@main

      - name: Checkout PR branch
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          GH_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: gh pr checkout "$PULL_REQUEST"

      - name: Pull bottles
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          ECMWF_TOOLBOX_TOKEN: ${{ secrets.ECMWF_TOOLBOX_TOKEN }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: >
          brew pr-pull
          --debug
          --clean
          --no-cherry-pick
          --workflows=tests.yml
          --tap="$GITHUB_REPOSITORY"
          --root-url="https://ghcr.io/v2/recmanj-org/homebrew-ecmwf"
          "$PULL_REQUEST"

      - name: Push bottle commits to PR branch
        uses: Homebrew/actions/git-try-push@main
        with:
          directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
          branch: ${{ github.event.pull_request.head.ref }}

      - name: Approve PR
        env:
          GH_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: gh pr review --approve "$PULL_REQUEST"

      - name: Merge PR
        env:
          GH_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: gh pr merge --merge "$PULL_REQUEST"
