name: brew test-bot bottles

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  checks: read
  contents: read
  issues: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}

jobs:
  syntax:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

  test-bot:
    needs: syntax
    if: ${{ github.event_name == 'pull_request' && github.triggering_actor != 'github-actions[bot]' }}
    env:
      ECMWF_TOOLBOX_TOKEN: ${{ secrets.ECMWF_TOOLBOX_TOKEN }}
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26
          - macos-26-intel
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: brew install-bundler-gems

      - name: Configure git credentials for private repos
        run: |
          echo "https://x-access-token:${ECMWF_TOOLBOX_TOKEN}@github.com" >> ~/.git-credentials
          git config --global credential.helper store

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - name: Build bottles
        run: brew test-bot --only-formulae --fail-fast

      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: bottles_${{ matrix.runner }}
          path: "*.bottle.*"
